### ISSUE TITLE
Windows Phone 8.1 throwing a exception

### ISSUE THREAD

**Issue by jefersonkallynsr** [jamesmontemagno/ImageCirclePlugin#11]
## Bug

Version Number of Xamarin.Forms: 2.3.2.127
Version Number of Plugin: 1.6.1
Device Tested On: Lumia 520 and 
Simulator Tested On: Windows Phone 8.1 simulators from Visual Studio
### Expected Behavior

The page must be loaded and display the circular image, bordered or borderless, or any other feature supported by the plugin.
### Actual Behavior

When loading the page is requested by the Windows Phone 8.1 (physical device or emulator), an exception is displayed: **Could not load type 'Xamarin.Forms.Platform.WinRT.StreamImagesourceHandler' from assembly 'Xamarin.Forms.Platform.WinRT, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.**
### Steps to reproduce the Behavior

Load the page on a device or simulator with the operating system Windows Phone 8.1

**Comment by jefersonkallynsr** [comment]
James, implementing your code directly into a Custom Renderer I realized that some things were only writing differences, so was giving problem such as, "StreamImagesourceHandler" where the Source S is tiny and at the end of code which has "ImageLoaderSourceHandler ()", which is not found by Visual Studio.

(I'm sorry for my bad english)

[ImageCirclePlugin - Windows Phone RT](https://github.com/jamesmontemagno/ImageCirclePlugin/blob/master/src/ImageCircle.Forms.Plugin.WindowsPhoneRT/ImageCircleRenderer.cs)

**Comment by jefersonkallynsr** [comment]
Thanks for the update!

**Comment by jamesmontemagno** [comment]
Yup, it was a change in the Forms API
