### ISSUE TITLE
Error when running iOS app with ImageCirclePlugin added in Xamarin

### ISSUE THREAD

**Issue by mkostersitz** [jamesmontemagno/ImageCirclePlugin#12]
I have add the package to both the shared/PCL and the iOS project in my app. It builds fine but when running the app in Debug both on device and simulator I get
Could not load file or assembly 'ImageCircle.Forms.Plugin.Abstractions' or one of its dependencies thrown in Main.cs on the iOS project
## Bug

Version Number of Plugin: 1.8.0.5
Device Tested On: iPhone 6s Plus iOS 10
Simulator Tested On: iPhone 6SE iOS 10
### Expected Behavior

The project to run
### Actual Behavior

Could not load file or assembly 'ImageCircle.Forms.Plugin.Abstractions' or one of its dependencies
### Steps to reproduce the Behavior

Add package to the projects
Add xmlns and circleImage object to XAML in shared project
Add code in codebehind for XAML to populate the image
build for debug on device or simulator
Observe error when app starts

**Comment by jamesmontemagno** [comment]
In your iOS, Android, and Windows projects call:

Xamarin.Forms.Init();//platform specific init
ImageCircleRenderer.Init();

Final Builds For linking you may need to add:

Android:

ImageCircle.Forms.Plugin.Abstractions;ImageCircle.Forms.Plugin.Android;

iOS:

--linkskip=ImageCircle.Forms.Plugin.iOS --linkskip=ImageCircle.Forms.Plugin.Abstractions

this is in the readme

**Comment by mkostersitz** [comment]
Thanks I must have accidentially deleted it after adding the line.

Mike
