### ISSUE TITLE
Image Circle not importing on Xamarin Studio but working fine on Visual Studio

### ISSUE THREAD

**Issue by MehrozeYaqoob** [jamesmontemagno/ImageCirclePlugin#16]
I am using the latest version released on 6 January 2017. When I deploy my app from windows to iOS Simulator, it works fine but when I use the same code in xamarin studio, it givee me error.

Project/iOS/MTOUCH: Error MT2002: Failed to resolve "System.Void Xamarin.Forms.Xaml.XamlFilePathAttribute::.ctor(System.String)" reference from "Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" (MT2002) (Project.iOS)

Error reference leads me to this page https://developer.xamarin.com/guides/ios/troubleshooting/mtouch-errors/#MT2002

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Are you sure you have the same version of Xamarin.Forms installed in each of your projects?

**Comment by MehrozeYaqoob** [comment]
Yup Xamarin Forms version is same. I managed to solved it by 

- Removing all the Nuget Packages from PCL, Android Project and iOS Project.
- Re-install All Nuget Packages to PCL, Android and iOS
- Problem solved. 
- Kudos to the owner of Image Circle Package 

Thanks
