### ISSUE TITLE
Bug on iOS, image circle doesn't work

### ISSUE THREAD

**Issue by michelviveiros** [jamesmontemagno/ImageCirclePlugin#18]
Hello Guys, I did everything correct of the tutorial and the image works on Android, but in iOS the image stretch horizontally and turns into a oval image. 

Version Number of Plugin: Last
Device Tested On: iPhone 6 Plus

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/ImageCirclePlugin/issues/15
