### ISSUE TITLE
Error "too many files open" on large list of images

### ISSUE THREAD

**Issue by vhugogarcia** [jamesmontemagno/ImageCirclePlugin#20]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.8.1
Device Tested On: iPhone 6
Simulator Tested On: iPhone 5S

### Expected Behavior
While rendering large listing of circle images, all should be fast and smooth.

### Actual Behavior
While rendering large listing of circle images it crashes and it sends the following message: "Too many files open"

### Steps to reproduce the Behavior
Load more than 400 images retrieved from different urls and render them in a listview in Xamarin.forms.

**Comment by jamesmontemagno** [comment]
This is most likely not an issue with this plugin at all, doing that with so many images you could be running out of memory. The plugin uses the native renderer under the hood so you may want to look at FFImageLoader if you have that many images.
