### ISSUE TITLE
CircleImage inside CircleImage?

### ISSUE THREAD

**Issue by Smiljke** [jamesmontemagno/ImageCirclePlugin#23]
Is it possible to set image inside image?

Example:
xmlns:ImageCircle="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"

**<ImageCircle:CircleImage FillColor={Binding RandomColor} HeightRequest="48" WidthRequest="48">**
      _<Image:CircleImage Source={Binding PictureWithoutBackground} HeightRequest="30" WidthRequest="30"/>_
**< ImageCircle:CircleImage />**

**Comment by jamesmontemagno** [comment]
No, you would want some other custom view to do circles, not an image as there is overhead.
