### ISSUE TITLE
Why the image circle is crushed?

### ISSUE THREAD

**Issue by biapar** [jamesmontemagno/ImageCirclePlugin#25]
Hi,

I tried some height and width but I see alway the image crushed. Why?
The image is into a grid cell. 
I tried to config the row height, too.

![image](https://cloud.githubusercontent.com/assets/661517/25605416/f0412cde-2f0a-11e7-95dc-7058564dfb6a.png)

**Comment by jamesmontemagno** [comment]
without the code can't be sure, but make sure that you have things set to fill and expand for height and width.

**Comment by biapar** [comment]
This is the code:
 <imagecircle:CircleImage IsVisible="{Binding IsBusy}" x:Name="Avatar" Grid.Column="0" FillColor="{DynamicResource Primary}" 
                                       Source="{Binding AvatarUrl}"
                                       VerticalOptions="Center"
                                       Aspect="AspectFill">
                        <imagecircle:CircleImage.WidthRequest>
                            <OnPlatform x:TypeArguments="x:Double" iOS="20" Android="20" WinPhone="20"/>
                        </imagecircle:CircleImage.WidthRequest>
                        <imagecircle:CircleImage.HeightRequest>
                            <OnPlatform x:TypeArguments="x:Double" iOS="20" Android="20" WinPhone="20"/>
                        </imagecircle:CircleImage.HeightRequest>
                    </imagecircle:CircleImage>

**Comment by oridotaoyebode** [comment]
@biapar did you find a solution to this?

**Comment by oridotaoyebode** [comment]
found a solution. Mark your parent control with FillAndExpand for HorizontalOptions and VerticalOptions
@biapar @jamesmontemagno
