### ISSUE TITLE
Images are showing but no circle is appearing.

### ISSUE THREAD

**Issue by appledevice24** [jamesmontemagno/ImageCirclePlugin#26]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

### Actual Behavior
Images are showing but no circle is appearing.
### Steps to reproduce the Behavior
Images are showing but no circle is appearing.

I did all steps except the call to ImageCircleRenderer.Init();. it is giving me error as not found, 
Please provide sample example.

## Feature Request:
Please fill in what you would like

**Comment by kp-xcess** [comment]
On what platform are you experiencing this issue?

**Comment by appledevice24** [comment]
I am using it on Android, (4.4).  I am using Portable Library. I am new to Xamarin development. Here is my xaml file code. 
<<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"....
xmlns:controls="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"

----------------------------
                              <controls:CircleImage Grid.Row="0" Grid.RowSpan="3" Grid.Column="0" Source="{Binding Base64Image, Converter={StaticResource Base64ToImageConverter}}" Aspect="AspectFill">
                                    <controls:CircleImage.WidthRequest>
                                        <OnPlatform x:TypeArguments="x:Double"
                                  iOS="55"
                                  Android="55"
                                  WinPhone="75"/>
                                    </controls:CircleImage.WidthRequest>
                                    <controls:CircleImage.HeightRequest>
                                        <OnPlatform x:TypeArguments="x:Double"
                                  iOS="55"
                                  Android="55"
                                  WinPhone="75"/>
                                    </controls:CircleImage.HeightRequest>
                                </controls:CircleImage>

I did not call ImageCircleRenderer.Init() anywhere. Is that a problem? What is the right place to call?

**Comment by Anik1991** [comment]
I also face the same problem and platform is same as him.
```
<controls:CircleImage Source="http://imgsv.imaging.nikon.com/lineup/lens/zoom/normalzoom/af-s_dx_18-140mmf_35-56g_ed_vr/img/sample/sample1_l.jpg" Aspect="AspectFill" BorderColor="Blue" BorderThickness="5">
                <controls:CircleImage.WidthRequest>
                    <OnPlatform x:TypeArguments="x:Double" iOS="55" Android="55"/>
                </controls:CircleImage.WidthRequest>
                <controls:CircleImage.HeightRequest>
                    <OnPlatform x:TypeArguments="x:Double" iOS="55" Android="55"/>
                </controls:CircleImage.HeightRequest>
            </controls:CircleImage>
```
also I also call ImageCircleRenderer.Init() in android.

**Comment by jamesmontemagno** [comment]
You need to call that in your MainActivity.cs

**Comment by appledevice24** [comment]
Getting error: 

Error	CS0103	The name 'ImageCircleRenderer' does not exist in the current context	

What need to be included to resolve this error.

**Comment by jamesmontemagno** [comment]
Did you install the nuget?

it lives in ImageCircle.Forms.Plugin.Droid namespace

**Comment by appledevice24** [comment]
Yes I did. 

![image](https://cloud.githubusercontent.com/assets/24705934/26124110/2812d950-3a32-11e7-8775-c3e34f9920a6.png)

**Comment by jamesmontemagno** [comment]
It didn't install the Android dll... try ininstall and reinstall maybe...

https://github.com/jamesmontemagno/ImageCirclePlugin/blob/master/nuget/Plugin.nuspec#L67-L73

there are 2 dlls that need to get installed.

**Comment by appledevice24** [comment]
ok. Got working now. Missed step, -> Installed nuget for Android. Right click on Android Project -> references -> Search ImageCircle -> Install

Thank you
