### ISSUE TITLE
Not Working in iOS 5s

### ISSUE THREAD

**Issue by Dan27F** [jamesmontemagno/ImageCirclePlugin#29]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:1.8.1
Device Tested On: 
Simulator Tested On: Simulator iOS 5s

### Expected Behavior
Render Circle Image
### Actual Behavior
Not working
### Steps to reproduce the Behavior
`<Grid.RowDefinitions>
				<RowDefinition Height="100"></RowDefinition>
				<RowDefinition Height="1"></RowDefinition>
				<RowDefinition Height="2*"></RowDefinition>
			</Grid.RowDefinitions>
            <controls:CircleImage BackgroundColor="Red" x:Name="imgPerfil" Source="{Binding avatar}" Aspect="AspectFill">
              <controls:CircleImage.WidthRequest>
                <OnPlatform x:TypeArguments="x:Double"
                  iOS="70"
                  Android="70"
                  WinPhone="75"/>
               </controls:CircleImage.WidthRequest>
            <controls:CircleImage.HeightRequest>
                <OnPlatform x:TypeArguments="x:Double"
                  iOS="70"
                  Android="70"
                  WinPhone="75"/>
               </controls:CircleImage.HeightRequest>
            </controls:CircleImage>`
Inside Grid

![error_img](https://cloud.githubusercontent.com/assets/23321210/26317499/a9341974-3ee5-11e7-9555-870c8905e6e0.png)

Link Img: https://s3-us-west-2.amazonaws.com/senador-virtual/avatars/9fbef5997f4c50df9ea6dfc4a0101a68.jpg
## Feature Request:
Please fill in what you would like
Working

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/ImageCirclePlugin/issues/25
