### ISSUE TITLE
Transparent images are not round on Windows UWP

### ISSUE THREAD

**Issue by ozzy1873** [jamesmontemagno/ImageCirclePlugin#3]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Transparent images are not round on Windows UWP

Version Number of Plugin: 1.4.1
Device Tested On: None
Simulator Tested On: 10.0.10568.0 WXGA 4.5 inch 1GB
### Expected Behavior

Image should be round.
### Actual Behavior

Image is oval even though the png is square. Image is a transparent png with more space to the left
and right of the non-transparent part of the image than on the top and bottom. (see attached)
### Steps to reproduce the Behavior

![noavatar](https://cloud.githubusercontent.com/assets/8699636/16708648/818fc0de-45b8-11e6-875b-f89cf47f7940.png)

**Comment by jamesmontemagno** [comment]
Can you take a screenshot of it in the app so I can see the behavior?

**Comment by jamesmontemagno** [comment]
Not enough information here, closing for now.
