### ISSUE TITLE
FillColor property of ImageCirclePlugin is not working in iOS device

### ISSUE THREAD

**Issue by sandeshacharya7** [jamesmontemagno/ImageCirclePlugin#32]
Hi @jamesmontemagno 

Thank you for this wonderful plugin.

I am using nuget package of this plugin(version 1.8.1). 

FillColor property of ImageCirclePlugin is woking fine in Android device but not working in iOS device. iOS device doesn't display FillColor.

Is there any workaround for this?

**Comment by prashantvc** [comment]
@sandeshacharya7 do you see this issue with new version of plugin? Could you share the code snippet to reproduce this issue?

**Comment by jamesmontemagno** [comment]
Works for me just fine:

Control.BackgroundColor = ((CircleImage)Element).FillColor.ToUIColor(); is the code. it is there.
