### ISSUE TITLE
1.8.2.19 Wrong border stroke radius on iOS

### ISSUE THREAD

**Issue by taublast** [jamesmontemagno/ImageCirclePlugin#35]
This thing appears only on real iOS device. 
On Android it's ok. 
On iOS simulator debig/release it's ok.
On real iOS device DEBUG version it's ok. 
On real device RELEASE version this thing happens. See screenshot below. The wrong border radius. 

## Bug Information

Version Number of Plugin: 1.8.2.19 
Device Tested On: iPhone 5s 64gb - bug on release only, debug is okay
Simulator Tested On: 5s iOS 10.3 - works fine
Version of VS: 2017 15.2 latest community
Version of Xamarin: 2.3.4.247
Versions of other things you are using: ffimageloading 2.2.9

### Steps to reproduce the Behavior
see code below. set release version, test on real device.

### Expected Behavior
nice stroke at good position

### Actual Behavior
looks like a wrong radius, see screenshot below

### Code snippet

                                            <abstractions:CircleImage
                                                IsVisible="{Binding Image, Converter={StaticResource StringToVisibilityConverterNot}}"
                                                VerticalOptions="Center"
                                                HorizontalOptions="Center"
                                                Aspect="AspectFit"                                                
                                                Grid.Column="0"
                                                Margin="{StaticResource NewsAvatarMargin}"
                                                WidthRequest="50"
                                                HeightRequest="50"

                                                BorderColor="{x:Static appoMobi:AppColors.AccentLightest}"
                                                BorderThickness="1"
                                               
                                                Source="avatarserver.jpg"
                                                StyleId="avatar"
                                                />

### Screenshotst

![lol](https://user-images.githubusercontent.com/25801194/27452750-72042014-579c-11e7-8cc2-e2239ab56e2f.png)

**Comment by jamesmontemagno** [comment]
I will bump it to 2.0 as it may change the look and feel, but it was always a bit wrong and you may need to adjust it more:

https://github.com/jamesmontemagno/ImageCirclePlugin/pull/21
