### ISSUE TITLE
Use with FFImageLoading

### ISSUE THREAD

**Issue by tiscott1** [jamesmontemagno/ImageCirclePlugin#36]
Hey James,

I was curious if you've ever used your plugin with FFImageLoading. I know FFImageLoading has a circle transformation, but I much prefer the way your plugin works with regard to drawing an image inside a circle as opposed to cropping the image to a circle. If not, do you have a suggestion of where I might start?

**Comment by jamesmontemagno** [comment]
Since it is a customer render and theirs is a custom renderer you can't today unless you bring the source code into your app and inherit from their image type. 

I am thinking of moving this to be all attached properties in the future though so we will see :)
