### ISSUE TITLE
ImageSource.FromResource Not Working in UWP

### ISSUE THREAD

**Issue by hammad2224** [jamesmontemagno/ImageCirclePlugin#38]
When loading an image from PCL Xamarin Froms the image does not show up in UWP

## Bug Information

Version Number of Plugin: 1.8.2.19-beta
Device Tested On:Windows 10 64 Bit UWP
Simulator Tested On: Local Machine
Version of VS:  2015 Community 14.0.2542501 Update 3
Version of Xamarin: 2.3.4.247
Versions of other things you are using:

### Steps to reproduce the Behavior
1) Create an image folder in PCL Xamarin Forms
2) Put an image there and change image Build Action to Embedded Resource
3) Create a list view and in item template with other items add the circle image
<abstractions:CircleImage Margin="5" Aspect="AspectFill" WidthRequest="55" HeightRequest="55" Source="{Binding From.Photo}"/>
4) in app.xaml.cs add the following code
 List<Assembly> assembliesToInclude = new List<Assembly>();           assembliesToInclude.Add(typeof(ImageCircle.Forms.Plugin.UWP.ImageCircleRenderer).GetTypeInfo().Assembly);               assembliesToInclude.Add(typeof(ImageCircle.Forms.Plugin.Abstractions.CircleImage).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assembliesToInclude);
5) Run the app and image does not show
### Expected Behavior
Should show image like in Android
### Actual Behavior
Does not show image in UWP
### Code snippet
<ListView x:Name="LstCallRecords"  SelectedItem="{Binding CallSelected,Mode=TwoWay}" IsRefreshing="{Binding Refreshing}" RefreshCommand="{Binding RefreshCommand}" ItemsSource="{Binding CallRecords,Mode=OneWay }" IsPullToRefreshEnabled="True" HasUnevenRows="True" RowHeight="66">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <Grid>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="Auto" />
                                    <ColumnDefinition Width="Auto" />
                                    <ColumnDefinition Width="*" />
                                    <ColumnDefinition Width="Auto" />

                                </Grid.ColumnDefinitions>

                                <abstractions:CircleImage Margin="5" Aspect="AspectFill" WidthRequest="55" HeightRequest="55" Source="{Binding From.Photo}"/>

                                <Image WidthRequest="20" HeightRequest="20" Source="{Binding CallIcon}" Grid.Column="1"></Image>
                                
                                <StackLayout Grid.Column="2" VerticalOptions="CenterAndExpand" >
                                    <Label Text="{Binding From.Name}" Style="{StaticResource CallsNameLabel}" />
                                    <Label Text="{Binding CallReceivedTime}"  Style="{StaticResource CallsDateLabel}"  />
                                </StackLayout>

                                <StackLayout Grid.Column="3" VerticalOptions="Center" Orientation="Horizontal" >
                                    <Button Text="Text" FontSize="8" WidthRequest="44" HeightRequest="44"  ></Button>
                                    <Button Text="Call" FontSize="8" WidthRequest="44" HeightRequest="44"></Button>
                                </StackLayout>
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>

### Screenshotst

![list item using circle image](https://user-images.githubusercontent.com/10448430/27887820-a53550b4-61da-11e7-927c-b4d4b50f73b7.JPG)
![app xaml cs](https://user-images.githubusercontent.com/10448430/27887821-a7500876-61da-11e7-9a7d-e8e6239cff65.JPG)
![project json](https://user-images.githubusercontent.com/10448430/27887823-a9eb695e-61da-11e7-8ea7-c61270441625.JPG)
![display](https://user-images.githubusercontent.com/10448430/27887829-ace17220-61da-11e7-8ce8-c96fed843817.JPG)
![setting image from resource](https://user-images.githubusercontent.com/10448430/27887886-f0df8778-61da-11e7-9f45-62981b804560.JPG)

**Comment by jamesmontemagno** [comment]
Does this work if you just use the standard Image and not CircleImage?

**Comment by hammad2224** [comment]
Hi James,

Sorry my mistake image Build action was set to Embedded Resource which was causing the image not to display. changing the Build action on image resolved the issue and image circle works like a charm.

i have just one more question why the image is not as smooth from the edges as you can see in whatsApp round images?

Thanks
Regards,
Hammad Rafique

**Comment by jamesmontemagno** [comment]
They may be processing it different. Glad you got it working
