### ISSUE TITLE
Image not circle for UWP Windows 10

### ISSUE THREAD

**Issue by jacob-ebey** [jamesmontemagno/ImageCirclePlugin#4]
## Bug

Version Number of Plugin: 1.4.1
Device Tested On: Windows 10 UWP
Simulator Tested On: N/A
### Expected Behavior

Image should remain a Circle.
### Actual Behavior

Image is presented as a box.

Debug mode:
![debug](https://cloud.githubusercontent.com/assets/12063586/16748791/0efa64e2-477b-11e6-97a7-e34260120a62.PNG)

Release mode:
![release](https://cloud.githubusercontent.com/assets/12063586/16748872/7d90e9c6-477b-11e6-9aca-1553279ea40f.PNG)
### Steps to reproduce the Behavior

Enable Release mode.

The only difference between the two images above is Debug vs Release for a UWP application running on Windows 10.

**Comment by jamesmontemagno** [comment]
In release mode you need to make sure that it is not linked out during .NET Native. 

https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.UWP/App.xaml.cs#L116

**Comment by jacob-ebey** [comment]
Thank you @jamesmontemagno I realized this yesterday about 20 minutes after I posted. Appreciate the replay as always.

**Comment by ChrisMacLeanRQI** [comment]
Hello James.  We are experiencing this same issue when in release mode under Windows 10.  I looked at your above link and comment, but I am not sure what you mean by it.  It works fine in debug mode and on Android.

**Comment by jamesmontemagno** [comment]
You need to make sure you follow the readme and put in the Init and linkskip stuff
