### ISSUE TITLE
FillColor is lost with binding inside a listview

### ISSUE THREAD

**Issue by maciz84** [jamesmontemagno/ImageCirclePlugin#40]
Hi guys,

Firstly I would like to add that this is an awesome plugin, great job. The only issue/bug I have noticed is that when you try to use the control simply as a circle with no image and bind the fillcolor property inside of a listview, the color is lost when listview item is selected.

I currently have the below code inside my listview:

`                                                        <imagecircle:CircleImage WidthRequest="10" HeightRequest="10" VerticalOptions="Center"
                    FillColor="{Binding StatusName,Converter={StaticResource StatusToColorConverter}}"
                    IsVisible="True"/>`

It works perfectly until I select a row and then the fillcolor is lost. Any help on this would be much appreciated

**Comment by jamesmontemagno** [comment]
This is due to how iOS works for UITableView: https://stackoverflow.com/questions/6745919/uitableviewcell-subview-disappears-when-cell-is-selected
