### ISSUE TITLE
Error load image from REST (https)

### ISSUE THREAD

**Issue by carl-neng** [jamesmontemagno/ImageCirclePlugin#42]
Hi @jamesmontemagno 
I have a problem with load image on listview use mvvm binding 
<imgCircle:CircleImage
            BorderColor="#F2F2F2"
             BorderThickness="1"
             Source="{Binding UserImage}"
             HorizontalOptions="Center"
             VerticalOptions="StartAndExpand"
              WidthRequest="36" HeightRequest="36">
   </imgCircle:CircleImage>

Code behide:

 foreach (var items in leaveItems.Items)
                {
                    var listComplaint = new LeaveItem()
                    {
                        Id = items.Id,
                        EmployeeName = items.EmployeeName,
                        Reason = items.Reason,              
                        Al = items.LeaveTypeName,
                        TotalCount = _itemCount,
UserImage = ImageSource.FromUri(new Uri(ConstantImageUrl.ReadImage(items.EmployeeProfilePictureId)))
};
                    _leaveDataSource.Add(listComplaint);
}

Version Number of Plugin:
Device Tested On: iOS
Simulator Tested On: Device
Version of VS: 15.2 (26460.16)
Version of Xamarin: 2.3.4.247

But I got the error like this:
![photo_2017-08-09_16-04-24](https://user-images.githubusercontent.com/22851711/29116603-7eaec5a4-7d25-11e7-89bb-7875cf41aacf.jpg)

Please help me resolve this problem. Thank you advance.

**Comment by jamesmontemagno** [comment]
What happens if you use just an Image and not a CircleImage?

**Comment by carl-neng** [comment]
Yes exactly I will got this error also. So I want help me.

**Comment by jamesmontemagno** [comment]
If you get that issue also with just a normal Image it isn't with the plugin at all. i would escalate to the forums or to the bug tracker. Seems like a too long of file name or url perhaps.

**Comment by carl-neng** [comment]
Yes thank you so much. Now I know the reason for resolve it.
