### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by jurabek** [jamesmontemagno/ImageCirclePlugin#43]
Expected Behavior : 
Currently, we can use last Xamarin.Forms pre release version on .NET Standard, actually is it possible to create pre release CircleImagePlugin version for .NET Standard?

**Comment by jamesmontemagno** [comment]
You can already use it in a .NET Standard library by adding a line of code into the csproj: http://motzcod.es/post/148657853472/installing-a-pcl-into-netstandard-libraries

When forms has it's main version out I will swap over.
