### ISSUE TITLE
CircleImage doesnt work on UWP with -scale images

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/ImageCirclePlugin#47]
Hello @jamesmontemagno .

Please look at this image.

![image](https://user-images.githubusercontent.com/32128644/30639790-fad6d74e-9e08-11e7-8c3d-2b5688278410.png)

App.cs

protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;
            var rendererAssemblies = new[] { typeof(ImageCircleRenderer).GetTypeInfo().Assembly };
            Xamarin.Forms.Forms.Init(e, rendererAssemblies);
            ImageCircleRenderer.Init();

**Comment by prashantvc** [comment]
@Banger-win Could you fill out the following information? It will help us to troubleshoot this issue

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

- Steps to reproduce the Behavior
- Expected Behavior
- Actual Behavior
- Code snippet
- Screenshotst

**Comment by ghost** [comment]
Version Number of Plugin:  1.8.2.19 - beta
Device Tested On: only Local Machine
Simulator Tested On: only Local Machine
Version of VS: 14.0.25431.01 upd 3
Version of Xamarin: 4.7.5.1
Versions of other things you are using:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90150-00888-AA584
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-90150-00888-AA584
Microsoft Visual Basic 2015

Visual C# 2015   00322-90150-00888-AA584
Microsoft Visual C# 2015

Visual C++ 2015   00322-90150-00888-AA584
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-90150-00888-AA584
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 10   Build 104.0.20151101.164448
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Mono Debugging for Visual Studio   4.6.8-pre (ec7034f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.7.9.45 (bd7e3753c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   7.4.5.1 (fb018c5)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   11.0.0.0 (152b654)
Visual Studio extension to enable development for Xamarin.iOS.

Implementing on App.xaml.cs (UWP):
protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;
            var rendererAssemblies = new[] { typeof(ImageCircleRenderer).GetTypeInfo().Assembly };
            Xamarin.Forms.Forms.Init(e, rendererAssemblies);
            ImageCircleRenderer.Init();


Using in XAML (PCL):
xmlns:controls="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"


<controls:CircleImage Source="Assets/Images/tick.png"  HeightRequest="100" WidthRequest="100" Aspect="AspectFill" />


![image](https://user-images.githubusercontent.com/32128644/30681193-f690cd3a-9eac-11e7-8b16-3c6b484f13e3.png)

![image](https://user-images.githubusercontent.com/32128644/30681227-298c82ce-9ead-11e7-90f6-8ef1233fcf90.png)

**Comment by jamesmontemagno** [comment]
have you tried it without the scales on them?

**Comment by ghost** [comment]
@jamesmontemagno  working!!!

![image](https://user-images.githubusercontent.com/32128644/30693754-a6e66bc8-9ed9-11e7-8b98-6720f59c4ada.png)

Please answer how to be about Scales?

**Comment by jamesmontemagno** [comment]
I just wanted to make sure, I probably don't have the support in there for scale type images. Will look into it.
