### ISSUE TITLE
Circular images with border contain a small bit of color from the image

### ISSUE THREAD

**Issue by mikegottlieb** [jamesmontemagno/ImageCirclePlugin#5]
## Bug

When using the plugin along with a border the very edge of the circle contains a small bit of color from the image.
![image](https://cloud.githubusercontent.com/assets/2380086/17071003/08f7743a-502d-11e6-8310-b638bd41fcce.png)

Here is the use of the plugin in XAML
`<controls:CircleImage Source="{Binding MySource}"
                Aspect="AspectFill"
                                WidthRequest="45"
                HeightRequest="45"
                BorderThickness="5"
                BorderColor="White"
                FillColor="White"
                VerticalOptions="Center"
                HorizontalOptions="Start"
                Grid.Row="0"
                Grid.RowSpan="2"
                Grid.Column="1" />`

Version Number of Plugin: 1.4.1
Device Tested On: iPhone 6
Simulator Tested On: iPhone 6s iOS 9.3
### Expected Behavior

The purple image in the center should be displayed with just a white border that would blend into a white background.
### Actual Behavior

There is a slight purple border. The color of the border matches the color at the outskirts of the image so a similar thing happens when I use images of different colors.

**Comment by jamesmontemagno** [comment]
Hey mike, can you take a screenshot of the actual app, i am a bit confused here as to the issue.

What was the original image?

**Comment by mikegottlieb** [comment]
The original image was just the round purple icon that you see with a transparent background. The image I shared is from a screenshot. I can't easily go back to that state because I never committed those changes.

I ended up going with a homebrewed solution. I have a control that draws a rounded box view. Then I have a control that puts the image (with a transparent background) over the rounded box view. I keep their width and height settings pinned to each other to maintain the illusion of a border width. It isn't the prettiest, but it got the job done.

**Comment by brux88** [comment]
hello, I'm using this plugin on Android works perfectly on ios instead the border appears to be related to the width of the view:

`    <StackLayout  Orientation="Vertical">
        <StackLayout.HeightRequest>
          <OnPlatform x:TypeArguments="x:Double" Android="190" iOS="270"></OnPlatform>
        </StackLayout.HeightRequest>         
          <abstractions:CircleImage Source="{Binding Image}" BorderThickness="3"  WidthRequest="100" HeightRequest="100"
                                    BorderColor="{StaticResource primaryColor}" Aspect="AspectFit" >
          </abstractions:CircleImage>     
          <Label Text="bruno Madara" Margin="0,10,0,0" TextColor="White" HorizontalTextAlignment="Center" VerticalTextAlignment="Center" FontAttributes="Bold"></Label>
          <BoxView HeightRequest="1" Margin="10,0,10,0" HorizontalOptions="Fill" BackgroundColor="Gray" VerticalOptions="End"/>
      </StackLayout>`

![2017-01-16_1138](https://cloud.githubusercontent.com/assets/3495339/21979895/2ab95350-dbe1-11e6-8c70-5fbc7f74229b.png)
