### ISSUE TITLE
ImageCircle does not render as a circle in release mode for UWP.

### ISSUE THREAD

**Issue by ChrisMacLeanRQI** [jamesmontemagno/ImageCirclePlugin#50]
## Bug Information
  When compiled under release conditions, our UWP program does not render the ImageCircle control as a circle.  Rather, it appears as a square image.  It appears correctly under debug conditions, as well as in Android.

Version Number of Plugin:
  v2.0.0.36-beta
Device Tested On:
  Windows 10 with vs2017, Lumia 950XL (latest versions of OS)
Simulator Tested On:
  Mobile Emulator 10.0.15063.0
Version of VS: 
  VS Pro 2017 15.4.4
Version of Xamarin:
  2.5.0.91635

## XAML
        <Image x:Name="imgBusy" Grid.Row="1" Source="activity.png" HorizontalOptions="Center" VerticalOptions="Center" WidthRequest="100" HeightRequest="100"/>
        <controls:CircleImage x:Name="imgAudio" Grid.Row="1" HorizontalOptions="Center" VerticalOptions="Center">
            <controls:CircleImage.WidthRequest>
                <OnPlatform x:TypeArguments="x:Double"
                    iOS="75"
                    Android="75"
                    WinPhone="75"/>
            </controls:CircleImage.WidthRequest>
            <controls:CircleImage.HeightRequest>
                <OnPlatform x:TypeArguments="x:Double"
                    iOS="75"
                    Android="75"
                    WinPhone="75"/>
            </controls:CircleImage.HeightRequest>
        </controls:CircleImage>
``

**Comment by jamesmontemagno** [comment]
You must add

```
var rendererAssemblies = new[]
{
    typeof(ImageCircleRenderer).GetTypeInfo().Assembly
};
Xamarin.Forms.Forms.Init(e, rendererAssemblies);

```

**Comment by ChrisMacLeanRQI** [comment]
That got it.  Not sure how I missed that at the bottom.  Thanks a million.
