### ISSUE TITLE
Fail to install plugin to Xamarin.Forms (netstandard2.0)

### ISSUE THREAD

**Issue by balivo** [jamesmontemagno/ImageCirclePlugin#51]
## Bug Information

Version Number of Plugin: 1.8.1
Device Tested On: Not build
Simulator Tested On: Not build
Version of VS: 2017 v4.7.02556
Version of Xamarin: 4.8.0.753
Versions of other things you are using: Xamarin.Forms (2.5.0.121934)

### Steps to reproduce the Behavior
- Install plugin and error occurs

**Comment by jamesmontemagno** [comment]
What is the error?

**Comment by balivo** [comment]
Oh sorry... Wrong crop...

Shows message "This package cannot fully supported in netstandard 2.0..."

I'm trying recreate the project... Fallback support is configured...

**Comment by balivo** [comment]
![ScreenShot Error](https://user-images.githubusercontent.com/6210814/34699834-b8dabed6-f4c6-11e7-97c4-9fde9df71202.png)

**Comment by jamesmontemagno** [comment]
Yeah, it should be fine because it is a PCL and it isn't a .net standard library yet.

**Comment by jamesmontemagno** [comment]
Also the 2.0 is built against .net standard
