### ISSUE TITLE
TargetInvocationException ---> Java.Lang.ClassNotFoundException: Didn't find class "md502d7e59f99e9102fa2e96096f27df83d.ImageCircleRenderer"

### ISSUE THREAD

**Issue by MichaelGiger** [jamesmontemagno/ImageCirclePlugin#53]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: V2.0.1
Device Tested On: Nokia 3
Simulator Tested On: no
Version of VS: 15.5.3
Version of Xamarin: 2.5.0.122203
Versions of other things you are using:

### Steps to reproduce the Behavior
I have created a new Cross-Platform App (Xamarin.Forms, Android Platform only and .Net Standard). After installing the NuGet packages in the .Net Standard and Adroid projects, I added ImageCircleRenderer.Init () to MainActivity. On MainPage.xaml I added the control (see code snippets)

### Expected Behavior
App starts and shows the MainPage.

### Actual Behavior
I get following exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Java.Lang.ClassNotFoundException: Didn't find class "md502d7e59f99e9102fa2e96096f27df83d.ImageCircleRenderer" on path: DexPathList[[zip file "/data/app/com.companyname.ImageCircleDemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.ImageCircleDemo-1/lib/arm64, /system/fake-libs64, /data/app/com.companyname.ImageCircleDemo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]] 

### Code snippet

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"
             x:Class="ImageCircleDemo.MainPage">

    <ContentPage.Content>
        <StackLayout>
            <controls:CircleImage BorderColor="Red" FillColor="Olive" BorderThickness="3" HeightRequest="150" WidthRequest="150" 
                                  Aspect="AspectFill" HorizontalOptions="Center" 
                                  Source="https://www.codeproject.com/KB/GDI-plus/ImageProcessing2/flip.jpg" />
        </StackLayout>

    </ContentPage.Content>

</ContentPage>
```

```
using Android.App;
using Android.Content.PM;
using Android.OS;
using ImageCircle.Forms.Plugin.Droid;

namespace ImageCircleDemo.Droid
{
    [Activity(Label = "ImageCircleDemo", Icon = "@drawable/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);

            ImageCircleRenderer.Init();

            LoadApplication(new ImageCircleDemo.App());
        }
    }
}

```

**Comment by prashantvc** [comment]
@MichaelGiger looks like you're hitting one of the know issue in the Xamarin.Android release https://github.com/xamarin/xamarin-android/pull/1142

You can find the workaround suggested here https://bugzilla.xamarin.com/show_bug.cgi?id=61073#c40

**Comment by MichaelGiger** [comment]
@prashantvc Thanks for your fast feedback!
I have replaced Xamarin.Android.Build.Tasks.dll (in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android), restarted the PC and still get the same exception!

StackTrace: https://gist.github.com/MichaelGiger/08d7af4588f1f6e5ed33f3cb4b9733ee

**Comment by jamesmontemagno** [comment]
And you did the .Init()?

**Comment by MichaelGiger** [comment]
Yes, see code snippet above.
Between global::Xamarin.Forms.Forms.Init(this, bundle); and LoadApplication(new ImageCircleDemo.App());

**Comment by jamesmontemagno** [comment]
I am not able to reproduce this at all. I don't think that it has to do with the error that @prashantvc listed. I am thinking that maybe it is your linker settings. Are you setting it to link all? You may want to add link skips so nothing gets stripped out. In the readme you can find this info.

**Comment by MichaelGiger** [comment]
I will check the linker settings.
Where (in code) do I have to add the link skips?

**Comment by prashantvc** [comment]
@MichaelGiger you can find the instructions to linkskip here https://developer.xamarin.com/guides/android/advanced_topics/linking/#linkskip

**Comment by MichaelGiger** [comment]
Adding "ImageCircle.Forms.Plugin.Abstractions;ImageCircle.Forms.Plugin.Android;" in "Skip linking assemblies" (Properties | Android Options) and all works fine!

Thanks for the tip...
