### ISSUE TITLE
[BUG] Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by nardoritos** [jamesmontemagno/ImageCirclePlugin#55]
I'm not sure if this is either a bug or a question, but this issue keeps happening whenever I try to load the CircleImage in anyway(XAML or Code-behind).

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.`

I did the Renderer.Init() in all of the projects and yet I seem to be the only one who this keeps happening to.

Thanks for the attention!

**Comment by jamesmontemagno** [comment]
Would need to see a full stack trace.
