### ISSUE TITLE
UWP: Method not found: 'CircleImage.set_BorderThickness(Int32)'

### ISSUE THREAD

**Issue by paleicikas** [jamesmontemagno/ImageCirclePlugin#59]
ImageCirclePlugin 2.0.2

<pre>System.MissingMethodException occurred
  Message=Method not found: 'Void ImageCircle.Forms.Plugin.Abstractions.CircleImage.set_BorderThickness(Int32)'.</pre>

Code:

<pre>new CircleImage
{
    BorderColor = ColorPalette.White.Background,
    BorderThickness = 2,
    Aspect = Aspect.AspectFill,
    IsOpaque = true,
    WidthRequest = 40,
    HeightRequest = 40,
    VerticalOptions = LayoutOptions.Start,
    HorizontalOptions = LayoutOptions.Start,
    Source = new UriImageSource
    {
        ...
    }
}</pre>

**Comment by jamesmontemagno** [comment]
Seems to work for me, tryout 3.0
