### ISSUE TITLE
StreamImageSource not working on UWP

### ISSUE THREAD

**Issue by sschutten** [jamesmontemagno/ImageCirclePlugin#6]
Version Number of Plugin: 1.4.1
Device Tested On: Surface Pro 3, Lumia 930

When using a stream as an image source (byte array for example) it remains blank on UWP, where it does work on Android and iOS. This seems to be fixed in the code on GitHub as it works as expected when I build the plugin from code. I can see in the code it uses the WindowsPhoneRT renderer, which now includes a StreamImageSource handler. Could it be this fix hasn't been released yet?

**Comment by jamesmontemagno** [comment]
Uploaded new NuGet :)

**Comment by sschutten** [comment]
I can confirm this works as expected now. You rock!
