### ISSUE TITLE
Issue on ios

### ISSUE THREAD

**Issue by Marsgames** [jamesmontemagno/ImageCirclePlugin#61]
## Bug Information

Version Number of Plugin: 2.0.2
Device Tested On: Samsung Galaxy Note 4
Simulator Tested On: iphone X
Version of VS: 7.3.3 build 17

Hey, i have an issue on ios when i'm trying to add my circle image at the center of my layout.

Here's my code : 
```C#
var stck = new StackLayout {
	Children = {
		new CircleImage{
			Source = source,
			WidthRequest = 64, MinimumWidthRequest = 64,
			HeightRequest = 64, MinimumHeightRequest = 64,
			BorderThickness = 1, BorderColor = Color.Black,
		},
		new StackLayout{
			Children = {
				new Label{ Text = " " },
				new Label{ 
					Text = user.User_Name_First, HorizontalOptions = LayoutOptions.Center,
					HorizontalTextAlignment = TextAlignment.Center 
				},
				new Label{ Text = " " },
			},
		},
	},
	Margin = new Thickness(10),
};
```

Here's the rendering on ios simulator :
![image](https://user-images.githubusercontent.com/9108765/36476995-ec3e76ea-16ff-11e8-87ca-339fb9899443.png)

Here's the rendering on Galaxy Note 4 : 
![image](https://user-images.githubusercontent.com/9108765/36477069-3590ac6e-1700-11e8-90dc-dabbeb05c9b8.png)

**Comment by jamesmontemagno** [comment]
Add HorizontalOptions = Center
