### ISSUE TITLE
Not working for iOS in Xamarin.Forms

### ISSUE THREAD

**Issue by mudassir93** [jamesmontemagno/ImageCirclePlugin#62]
I have just installed the latest version of the package from Nuget and added a reference Xamarin.Forms XAML. It is working for Android and showing the proper circular image with the border but when building for iOS it is showing the simple image.

## Bug Information

Version Number of Plugin: 2.0.2
Device Tested On iPhone 6S
Simulator Tested On: 
The version of VS: Enterprise 2017 for Mac
The version of Xamarin: Xamarin.iOS 11.8.0.20

Versions of other things you are using:

Xamarin.Android: 8.2.0.15
Visual Studio for Mac 7.4.0.1033

### Expected Behavior

Should show the circular image as it is showing on Android device and simulators.

### Actual Behavior

Working properly for Android but showing a simple image as it shows in Image Control for iOS.  

### Code snippet

```XAML
<ContentPage 
x:Class="App1.XYZMaster"  Title="Master" 
xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:circleImage="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions" >

<StackLayout VerticalOptions="End">
     <circleImage:CircleImage x:Name="UserImage"  FillColor="White" WidthRequest="70" 
        HeightRequest="70" BorderColor="White" BorderThickness="4" HorizontalOptions="Start" 
        VerticalOptions="EndAndExpand" Margin="20,0,0,10"/>
</StackLayout>

</ContentPage>```

### Screenshots

**Comment by jamesmontemagno** [comment]
Make sure you Init the control and set linker : https://github.com/jamesmontemagno/ImageCirclePlugin#final-builds

Works just fine.
