### ISSUE TITLE
Issue using local files on Android

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/ImageCirclePlugin#63]
## Bug Information

Version Number of Plugin: 2.0.2
Device Tested On: Android
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 2.5.0.280555
Versions of other things you are using:

### Steps to reproduce the Behavior

Follow sample guide which works correctly, then substitute the UriImageSource for a local file. Used same file linked to online in case there was an issue with an image I selected myself.

### Expected Behavior

Image is still circlified

### Actual Behavior

Image is nothingified

### Code snippet

circleImage.Source = ImageSource.FromFile("Tamarin_portrait.JPG");//Produced nothing/blank spot
(XAML) <controls:CircleImage x:Name="circleImage" Aspect="Fill" WidthRequest="40" HeightRequest="40"/>

Other XAML only attempts
(XAML) <controls:CircleImage x:Name="circleImage" Aspect="Fill" WidthRequest="40" HeightRequest="40" Source="Tamarin_portrait.JPG"/>
```
<controls:CircleImage Source="Tamarin_portrait.JPG" Aspect="AspectFill">
                    <controls:CircleImage.WidthRequest>
                        <OnPlatform x:TypeArguments="x:Double">
                            <On Platform="Android, iOS">55</On>
                            <On Platform="WinPhone">75</On>
                        </OnPlatform>
                    </controls:CircleImage.WidthRequest>
                    <controls:CircleImage.HeightRequest>
                        <OnPlatform x:TypeArguments="x:Double">
                            <On Platform="Android, iOS">55</On>
                            <On Platform="WinPhone">75</On>
                        </OnPlatform>
                    </controls:CircleImage.HeightRequest>
                </controls:CircleImage>
```
### Screenshots

(Nothing instead of something)

**Comment by prashantvc** [comment]
Where is image stored in the Android Project? For `ImageSource.FromFile` to work on Android the files need to be in `/Resources/drawable/` with Build Action: `AndroidResource`.

**Comment by ghost** [comment]
That is where I had stored the image and I just double checked and the Build Action is also set properly to AndroidResource.

**Comment by ghost** [comment]
I don't think this is an issue with the plugin now. I'm not able to show local images from the Xamarin tutorials either if I do it from the cs file.

var image = new Image { Source = "Tamarin_portrait.JPG" };
//Or image.Source = ImageSource.FromFile("Tamarin_portrait.JPG");
imageContainer.Children.Add(image);

Does not work for me, you can close down this bug, no idea why it's failing for me though. :<

**Comment by jamesmontemagno** [comment]
Could be some odd naming here.... Can you lowercase everything. If it is an issues for Image then it is on the XF side of things

**Comment by ghost** [comment]
Looks like that did it, it was an issue with the upper case character. Thanks.
