### ISSUE TITLE
Border does not encircle image

### ISSUE THREAD

**Issue by ebicoglu** [jamesmontemagno/ImageCirclePlugin#64]
## Bug Information

Version Number of Plugin:
Device Tested On: 0
Simulator Tested On: 1
Version of VS: 15.6.4
Version of Xamarin: 2.5.0.280555
Versions of other things you are using: ImageCirclePlugin v2.0.2

### Steps to reproduce the Behavior
Add this listview to any view... 

   <ListView 
                      SeparatorVisibility="None"  
                      HasUnevenRows="True"
                      ItemsSource="{Binding Users}" 
                      IsPullToRefreshEnabled="{Binding IsNotBusy}"
                      IsRefreshing="{Binding IsBusy}"
                      RefreshCommand="{Binding RefreshUsersCommand}"
                      ItemAppearing="ListView_OnItemAppearing"
                      SelectedItem="{Binding SelectedUser, Mode=TwoWay}"
                      CachingStrategy="RetainElement">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell >
                                <controls:CardView  Margin="10, 5, 10, 5" Padding="10" >

                                    <Grid  ColumnSpacing="16">
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="Auto"/>
                                            <ColumnDefinition Width="*"/>
                                        </Grid.ColumnDefinitions>

                                        <image:CircleImage 
                                            Source="{Binding Photo}" 
                                            WidthRequest="70" 
                                            HeightRequest="70" 
                                            Aspect="AspectFill"
                                            HorizontalOptions="CenterAndExpand" 
                                            BorderThickness="2"
                                            FillColor="White"
                                            BorderColor="{StaticResource PrimaryColor}">
                                        </image:CircleImage>

                                        <StackLayout VerticalOptions="Center" Grid.Column="1" Spacing="0">
                                            <Label Text="{Binding UserName}" Font="Bold"  Style="{StaticResource ActiveLabel}" />

                                            <StackLayout Orientation="Horizontal">
                                                <Label Text="{Binding Name}"  Style="{StaticResource ActiveLabel}"/>
                                                <Label Text="{Binding Surname}"  Style="{StaticResource ActiveLabel}"/>
                                            </StackLayout>

                                            <Label Text="{Binding EmailAddress}" FontSize="{StaticResource SmallFont}"  Style="{StaticResource ActiveLabel}"/>

                                        </StackLayout>

                                    </Grid>

                                </controls:CardView>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>

Note that I pasted the listview control as is. You can strip out the unnecessary tags.
This behavior has changed after I updated to v2.0.2

### Screenshotst
![image](https://user-images.githubusercontent.com/9526587/37907809-d8f4b5ee-310e-11e8-8985-e2de78b8cc4b.png)

PS: You misspelled **screenshots** in your "new issue template" :)

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarinhq/app-geocontacts/blob/master/src/GeoContacts/GeoContacts/Cells/ContactCell.xaml which works great
