### ISSUE TITLE
Not Support With .Net Standard Library

### ISSUE THREAD

**Issue by ronakshethia** [jamesmontemagno/ImageCirclePlugin#65]
Getting the below error when trying to add the library from nuget 

Package Xam.Plugins.Forms.ImageCircle 2.0.2 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package Xam.Plugins.Forms.ImageCircle 2.0.2 supports:

**Comment by eman1986** [comment]
seem to be working with .NETStandard 2.0 I'm not having any issues
