### ISSUE TITLE
Type controls:CircleImage not found in xmlns clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin

### ISSUE THREAD

**Issue by sebas3407** [jamesmontemagno/ImageCirclePlugin#67]
## Bug Information

Version Number of Plugin: 2.02
Device Tested On: iPhone SE
Simulator Tested On: iPhone 7
Version of VS: 7.5 (build 1254)
Version of Xamarin: 3.0

### Expected Behavior

The app should show a circle Image

### Actual Behavior

The app show the message: Type controls:CircleImage not found in xmlns clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin

### Code snippet

`xmlns:controls="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin"`

and

```

<controls:CircleImage Source="{Binding Image}" Aspect="AspectFill">
  <controls:CircleImage.WidthRequest>
    <OnPlatform x:TypeArguments="x:Double">
      <On Platform="Android, iOS">55</On>
      <On Platform="WinPhone">75</On>
    </OnPlatform>
  </controls:CircleImage.WidthRequest>
  <controls:CircleImage.HeightRequest>
    <OnPlatform x:TypeArguments="x:Double">
      <On Platform="Android, iOS">55</On>
      <On Platform="WinPhone">75</On>
    </OnPlatform>
  </controls:CircleImage.HeightRequest>
</controls:CircleImage>

```
### Screenshots

![image](https://user-images.githubusercontent.com/25606841/40968812-b7cde46e-68b6-11e8-8a02-653df05d962f.png)

**Comment by jamesmontemagno** [comment]
In 2.0 it is: assembly=ImageCircle.Forms.Plugin.Abstractions
