### ISSUE TITLE
Use a custom HttpClient when loading images from UriImageSource

### ISSUE THREAD

**Issue by AlexanderMelchers** [jamesmontemagno/ImageCirclePlugin#68]
Hi there,

We're currently considering migration from your old `Xam.Plugins.Forms.CachedImageCircle` to the `ImageCirclePlugin`, but one of our main obstacles in doing so is that we'd need more control over the way in which images are retrieved from our servers. That is, we'd like to be able to hook into the web call itself by way of a custom HttpClient, much in the same way as was possible with the old `CircleCachedImage` through hooking into `FFImageLoading`'s `ImageService`. To make this plug-in useful to us, I'd like to request this feature.

Kind regards,
Alexander.

**Comment by jamesmontemagno** [comment]
Use FFImageLoaders built in circle support. CachedImageCircle  is not mine
