### ISSUE TITLE
Support for image down-sampling

### ISSUE THREAD

**Issue by AlexanderMelchers** [jamesmontemagno/ImageCirclePlugin#69]
Hi all,

We're currently considering migration from your old `Xam.Plugins.Forms.CachedImageCircle` to this plug-in. However, one of the things I found to be lacking in the current implementation and which was really nice in the other plug-in was the option to down-sample images to save on memory. Is there any chance of this functionality coming to the current plug-in? Thanks!

Best regards,
Alexander.

**Comment by jamesmontemagno** [comment]
I have no plans to implement this. That is an unofficial control that was not by me.
