### ISSUE TITLE
Error handling when loading fails

### ISSUE THREAD

**Issue by AlexanderMelchers** [jamesmontemagno/ImageCirclePlugin#70]
Hi all,

Is there a way to detect when loading of an image (for example, from an `UriImageSource`) has failed, so that my application can respond by showing an error state? By way of comparison, `Xam.Plugins.Forms.CachedImageCircle` used to have this functionality, but the package is now so outdated that it is preventing us from updating our `FFImageLoading`-library. Thanks for your help!

Kind regards,
Alexander.

**Comment by jamesmontemagno** [comment]
You would have to provide a sample please. It is just an Image so Xamarin.Forms handles the loading.

**Comment by AlexanderMelchers** [comment]
Hi @jamesmontemagno,

I think this is just another part of the general confusion I had concerning the relationship between your plug-in and `Xam.Plugins.Forms.CachedImageCircle` (a case of mistaken identity, though for some reason the NuSpec of that package mentions your name as both author and owner), because `CachedImage` has an in-built `Error`-event we hook in to to explicitly load an error placeholder when an image fails to load.  haven't been able to figure out how to get the same functionality out of Xamarin's default `Image`-class or even out of `UriImageSource` (which is where I did find caching options). Thus, I think that unless Xamarin.Forms were to explicitly disclose this functionality (which, to my knowledge, is not something they do), this issue can also be closed, Sorry for the inconvenience!

Best regards,
Alexander.
