### ISSUE TITLE
No more FFImageLoading?

### ISSUE THREAD

**Issue by AlexanderMelchers** [jamesmontemagno/ImageCirclePlugin#71]
Hi all,

I'm not sure whether I've got the complete picture here, but it seems to me that this plug-in is the actively maintained offspring of the older `Xam.Plugins.Forms.CachedImageCircle`. That library used `FFImageLoading` to bring a lot of advanced image processing strategies to displaying a circular image. I was wondering why dependency/inheritance had been let go off...

All the best,
Alexander.

**Comment by jamesmontemagno** [comment]
This is the official package. Someone else created an unofficial version based on CachedImage which was very confusing because FFImageLoading has its own way to create a circle. so you don't need anything special so it was removed by the created who cloned this repo originally.

**Comment by AlexanderMelchers** [comment]
That explains! Thanks for clarifying!
