### ISSUE TITLE
Binding Issue on iOS

### ISSUE THREAD

**Issue by hossameldinmi** [jamesmontemagno/ImageCirclePlugin#72]
## Bug Information

Version Number of Plugin: 2.0.2
Device Tested On: iPhone 6s
Simulator Tested On: iPhone x 11.3
Version of VS: 2017
Version of Xamarin: Xamarin.Forms 3.0.0.482510
Versions of other things you are using: Prism.DryIoc.Forms 7.0.0.396
Prism.Forms 7.0.0.396

### Steps to reproduce the Behavior
Bind the Source property with ImageSource Property in ViewModel
I make a Tapped command to open Camera or pick a picture from media, and then after chose the image, and upload the image to the server and get it's url.
### Expected Behavior
the image should reflect immediately
### Actual Behavior
the new image doesn't reflect quickly, I have to go back and enter this page again
### Code snippet
Image = ImageSource.FromUri(Url);

**Comment by jamesmontemagno** [comment]
Would need a sample project and more source code.
