### ISSUE TITLE
Xamarin Forms IOS image is not circle when resizing

### ISSUE THREAD

**Issue by hajarrashidi** [jamesmontemagno/ImageCirclePlugin#73]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.0.5
Device Tested On: Iphone 7
Simulator Tested On: Iphone 8
Version of VS: 7.5.3
Version of Xamarin: 3.1.0.6
Versions of other things you are using:

### Steps to reproduce the Behavior
1. Create a Xamarin Forms project.
2. add the <controls:CircleImage>  and etc..
3. Make sure it works on Android. 

### Expected Behavior
It won't be round circle on IOS when i set width and height, it is round but then i can't choose the width & height, but the border is round
### Code snippet
`                <controls:CircleImage 
                x:Name="ProfilePicture"
                HeightRequest="200"
                WidthRequest="200"
                BorderColor="Red"
                BorderThickness="3"    
                ></controls:CircleImage>`
### Screenshots
<img width="834" alt="screenshot 2018-07-18 at 22 26 29" src="https://user-images.githubusercontent.com/4338882/42905995-fc32e02e-8ad9-11e8-9fa3-0617e5f55136.png">

**Comment by jamesmontemagno** [comment]
you most likely need to set your horizontal and vertical options

**Comment by hajarrashidi** [comment]
Thanks!
