### ISSUE TITLE
No Image in UWP Project 

### ISSUE THREAD

**Issue by KKirchhoff** [jamesmontemagno/ImageCirclePlugin#74]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: latest version 3.005
Device Tested On: IOS, Adroid and UWP
Simulator Tested On:
Version of VS: 2017 15.7.5 
Version of Xamarin: 3.1.0.697729
Versions of other things you are using:

Its the same issue, on uwp plattform no image are displayed.

**Comment by jamesmontemagno** [comment]
What type of resources are you using?
