### ISSUE TITLE
Not work on UWP

### ISSUE THREAD

**Issue by FBotte** [jamesmontemagno/ImageCirclePlugin#75]
Hi James

Version Number of Plugin: latest version 3.005
Device Tested On: IOS, Adroid and UWP
Version of Xamarin: 3.1.0.871581

Ok on iOS and Droid, Ko in UWP.

Images png from api deezer (binding source to url)

Thanks.

**Comment by jamesmontemagno** [comment]
Does it show up with a normal Image?

Do you have a url?
