### ISSUE TITLE
ImageCircle not appearing after updating to Android 9.0

### ISSUE THREAD

**Issue by albertpinhasov** [jamesmontemagno/ImageCirclePlugin#86]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.05
Device Tested On: -
Simulator Tested On: Android 8.1, and  9.0
Version of VS: 2019
Version of Xamarin: 4
Versions of other things you are using: 

### Steps to reproduce the Behavior
Implement ImageCircle in Android 8.1, run. It will work. 
Update to Android 9.0 it will show empty circle. (I added border)
### Expected Behavior
Image should appear inside a circle shape
### Actual Behavior
image not rendered
### Code snippet

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:controls="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin"
             mc:Ignorable="d"
             x:Class="ic.Views.roundImage">
    <ContentPage.Content>
        <StackLayout>
            
            <controls:CircleImage x:Name="_imgCircle" WidthRequest="50" Source="http://lorempixel.com/100/100/people/1"  HeightRequest="50" BorderColor="Blue" BorderThickness="3" Aspect="AspectFit"></controls:CircleImage>
            
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```
### Screenshots

![Screenshot 2019-05-27 08 49 08](https://user-images.githubusercontent.com/46766402/58420844-5e5cd700-805c-11e9-8cae-eea025727758.png)

**Comment by jamesmontemagno** [comment]
This is because Android 9 blocks http traffic by default: https://devblogs.microsoft.com/xamarin/cleartext-http-android-network-security/
