### ISSUE TITLE
[Bug] Circle Image not correctly rendering (while in a horizontal StackLayout?)

### ISSUE THREAD

**Issue by MarcusOy** [jamesmontemagno/ImageCirclePlugin#88]
Hi there,
I am trying to use this plugin, however, I cannot get the circle image to render properly. See screenshots. I believe it has to do with the parent containers it is in. It starts in a Frame, which has the content of a Grid (first row with a GridLength of 0.45 out of 1.0 and GridUnitType on Star), then it is in a StackLayout that is Horizontal.

Edit: just tested making a circle image in a ScrollView with content being a normal StackLayout, it works fine.

## Bug Information

Version Number of Plugin: 3.0.0.5
Device Tested On: None
Simulator Tested On: iPhone 7 and XR
Version of VS: VS for Mac 8.0.5 (Build 9)
Version of Xamarin: 4.0.0.482894

### Steps to reproduce the Behavior
I used starter code. Nothing else.
### Expected Behavior
Renders correctly
### Actual Behavior
The image used can be seen outside of the circle
### Code snippet
This happens on the code listed in the Readme.md, however I was trying different settings and the result is the same every time.
```

            this.frameGrid = new Grid
            {
                RowDefinitions =
                {
                    new RowDefinition{Height = new GridLength(0.45, GridUnitType.Star) },
                    new RowDefinition{Height = new GridLength(0.55, GridUnitType.Star) }
                }
            };
```

```
            this.image = new CircleImage
            {
                BorderColor = Color.White,
                BorderThickness = 3,
                HeightRequest = 40,
                WidthRequest = 40,
                Aspect = Aspect.AspectFit,
                HorizontalOptions = LayoutOptions.Center,
                Source = ImageSource.FromUri(new Uri("https://techcrunch.com/wp-content/uploads/2018/07/logo-2.png"))
            };
```

```
            this.frameGrid.Children.Add(new StackLayout
            {
                Orientation = StackOrientation.Horizontal,
                Children =
                {
                    this.image,
                    new StackLayout
                    {
                        Orientation = StackOrientation.Vertical,
                        Spacing = 0,
                        Children =
                        {
                            // Label,
                            // Label
                        }
                    }
                }
            }, 0, 0);
```

### Screenshots

<img width="435" alt="Screen Shot 2019-06-29 at 10 43 41 AM" src="https://user-images.githubusercontent.com/16263577/60386519-6644d800-9a5b-11e9-8648-283da2260047.png">

**Comment by jamesmontemagno** [comment]
would need a sample project if you have it and can then see. This seems like it should work just fine as I have used horizontal stacks all the time. You could also put it in a grid.

**Comment by MarcusOy** [comment]
I switched to another library because I couldn’t figure out the problem myself. Sorry :(

________________________________
