### ISSUE TITLE
[Feature Request] FFImageLoading Support

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/ImageCirclePlugin#9]
## Feature Request:

Currently no way to use this control and FFImageLoading's CachedImage control together. 

Figure out a new package that can sit on top of this.

**Comment by toadzky** [comment]
FYI, it looks like someone forked this project to add this, but it's published on nuget with you as the author. https://github.com/fferegrino/CachedImageCirclePlugin

**Comment by jamesmontemagno** [comment]
This is actually not needed at all because it is built in: https://github.com/luberda-molinet/FFImageLoading/wiki/Transformations-Guide
